### PR TITLE
U64 max

### PR DESCRIPTION
**Pull request by dvc94ch**

### CODE REVIEW

**Comment by wngr** [comment]
Seems there is no automagic conversion to BigInts if the value is > 32 bits. wasm-bindgen splits the 64 bit values into two 32 bit values, and patches them up again on the js side using a BigUint32Array with the two values, and then `BigUint64Array(32bitarray.buffer)[0]`.
[Emscripten](https://v8.dev/features/wasm-bigint#the-solution%3A-javascript-bigints) is able to do it, but rustc apparently not.

**Comment by wngr** [comment]
Shall we do the "legalization" too or do you have another idea? You can always stringify it :trollface:

**Comment by dvc94ch** [comment]
not sure. maybe do (~x - 1) if an unsigned number is < 0?

**Comment by wngr** [comment]
So running the same test with i64 on node v14 yields (as expected):
```
STDERR:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
/tmp/.tmpIzl1Iu:101
        const ret = this.instance.exports.__i64_max(
                                          ^

TypeError: wasm function signature contains illegal type
    at Api.i64_max (/tmp/.tmpIzl1Iu:101:43)
    at main (/tmp/.tmpIzl1Iu:123:22)
thread 'main' panicked at 'assertion failed: ret', /tmp/.tmpOS1J3G:32:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So I think we have to do a conversion using 2 32 byte values

**Comment by wngr** [comment]
I guess I can fix that once you're done with your refactoring.

**Pull request closed without merging**
